#!/bin/sh
# © 2019 Keith Maxwell
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain
# one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
# SPDX-Copyright: 2019 Keith Maxwell
#
if ! find packages -name main.yaml -exec printf '- import_playbook: {}\n' \; |
sort |
cmp - site.yaml > /dev/null; then
	printf 'site.yaml is incorrect\n'
	exit 1
fi
