- name: Install {{ playbook_dir | basename }} application with pip
  hosts: all
  pre_tasks:
    - name: Install dependencies with compiled extensions on Alpine Linux
      apk:
        name:
          - "py3-lxml{{ apk_version | default('~4.6.1')}}" # ./requirements.in
        repository:
          - http://dl-cdn.alpinelinux.org/alpine/edge/main
          - http://dl-cdn.alpinelinux.org/alpine/edge/community
      when: ansible_distribution == 'Alpine'
  roles: [pip]
