# © 2020 Keith Maxwell
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain
# one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
# SPDX-Copyright: 2019 Keith Maxwell
alpine-edge-ansible:
  stage: build
  image: quay.io/buildah/stable
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:alpine
  before_script:
    - echo -e "section_start:$(date +%s):site\r\e[0KSet up buildah"
    - buildah --version
    - >2-
      buildah login
      --username gitlab-ci-token
      --password $CI_BUILD_TOKEN
      $CI_REGISTRY
  script: >2-
    echo -e "section_start:$(date +%s):site\r\e[0KBuild container"
    && container=$(buildah from alpine:edge)
    && buildah run $container -- apk upgrade
    && buildah run $container -- apk add ansible py3-virtualenv nodejs npm
    && buildah run $container -- ansible --version
    && buildah run $container -- virtualenv --version
    && buildah commit $container $IMAGE_TAG
  after_script: [buildah push $IMAGE_TAG]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

.alpine:
  stage: test
  image: $CI_REGISTRY_IMAGE:alpine
  before_script: [chmod o-w .]
  script: >2-
    ansible-playbook
    -c local
    -i localhot,
    -v
    packages/$CI_JOB_NAME/main.yaml

black: { extends: .alpine }
embedme: { extends: .alpine }
fava: { extends: .alpine }
flake8: { extends: .alpine }
git-filter-repo: { extends: .alpine }
git-revise: { extends: .alpine }
hovercraft: { extends: .alpine }
isort: { extends: .alpine }
instaloader: { extends: .alpine }
js-yaml: { extends: .alpine }
lint-staged: { extends: .alpine }
litecli: { extends: .alpine }
prettier: { extends: .alpine }
pip-tools: { extends: .alpine }
uncommitted: { extends: .alpine }
