# © 2019 Keith Maxwell
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain
# one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
# SPDX-Copyright: 2019 Keith Maxwell
#
alpine-edge:
  image: alpine:edge
  before_script:
    - ./.githooks/pre-commit
    - chmod o-w .
    # on edge the container image and the repo mirrors may not be in sync
    # upgrading here avoids any errors that would show via ldd
    - apk update
    - apk upgrade
    - apk add ansible py3-pip
    - ansible --version
  script: ["ansible-playbook -i, site.yaml"]

# Installing Ansible on Ubuntu and Debian is based upon the official
# instructions at https://docs.ansible.com/ansible/latest/installation_guide/
# To avoid a warning about an unstable command line interface, apt-get is used
# in place of apt.

# python-apt and aptitude are required for Ansible's package and apt modules
# these are used for example in ./roles/npm/tasks/node-distribution.yaml and
# ./roles/pip/tasks/main.yaml

ubuntu-bionic:
  image: ubuntu:bionic
  before_script:
    - chmod o-w .
    - apt-get update
    - apt-get upgrade --yes
    - apt-get install --yes software-properties-common
    - apt-add-repository --yes --update ppa:ansible/ansible
    - apt-get install --yes ansible python-apt aptitude
    - ansible --version
  script: ["ansible-playbook -i, site.yaml"]

debian-stretch:
  image: debian:buster
  before_script:
    - chmod o-w .
    - apt-get update
    - apt-get upgrade --yes
    - apt-get install --yes gnupg
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    - printf 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main\n'
      > /etc/apt/sources.list.d/ansible.list
    - apt-get update
    - apt-get install --yes ansible python-apt aptitude
    - ansible --version
  script: ["ansible-playbook -i , site.yaml"]
