# © 2019 Keith Maxwell
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain
# one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
# SPDX-Copyright: 2019 Keith Maxwell
#
alpine-edge:
  image: alpine:edge
  before_script:
    - ./.githooks/pre-commit
    - chmod o-w .
    # on edge the container image and the repo mirrors may not be in sync
    # upgrading here avoids any errors that would show via ldd
    - apk update
    - apk upgrade
    - apk add ansible
    - ansible --version
  script: ["ansible-playbook -i, site.yaml"]

ubuntu-bionic:
  image: ubuntu:bionic
  before_script:
    - chmod o-w .
    - apt-get update
    - apt-get install --yes software-properties-common
    - apt-add-repository --yes --update ppa:ansible/ansible
    - apt-get install --yes ansible python-apt aptitude # for package and apt modules
    - ansible --version
  script: ["ansible-playbook -i, site.yaml"]

debian-stretch:
  image: debian:buster
  before_script:
    - chmod o-w .
    - printf 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main\n'
      > /etc/apt/sources.list.d/ansible.list
    - apt-get update
    - apt-get install --yes gnupg
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    - apt-get update
    - apt-get install --yes ansible python-apt aptitude # for package and apt modules
    - ansible --version
  script: ["ansible-playbook -i , site.yaml"]
