# © 2019 Keith Maxwell
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain
# one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
# SPDX-Copyright: 2019 Keith Maxwell
#
- name: Create a package.json
  hosts: localhost
  gather_facts: no
  vars:
    create_json: |
      {
        "name": "installed-with-ansible",
        "version": "1.0.0",
        "description": "Installed by Ansible",
        "main": "index.js",
        "dependencies": {
          "{{ create_package }}": "{{ create_query.json.latest }}"
        },
        "repository": {
          "type": "git",
          "url": "git+https://gitlab.com/maxwell-k/applications.git"
        },
        "author": "Keith Maxwell",
        "license": "Apache-2.0",
        "bugs": {
          "url": "https://gitlab.com/maxwell-k/applications/issues"
        },
        "homepage": "https://gitlab.com/maxwell-k/applications#readme"
      }
  tasks:
    - name: Package must be defined
      assert: { that: create_package is defined }
    - name: Create a directory
      file: { state: directory, path: "packages/{{ create_package }}" }
    - name: Query the registry
      uri:
        url: https://registry.npmjs.org/-/package/{{ create_package }}/dist-tags
        return_content: yes
      register: create_query
    - name: Create a package.json
      copy:
        dest: "packages/{{ create_package }}/package.json"
        mode: 0o644
        content: "{{ create_json | to_nice_json }}"
    - name: Create a main.yaml
      copy:
        dest: "packages/{{ create_package }}/main.yaml"
        mode: 0o644
        content: |
          - name: {{ create_package }}
            hosts: localhost
            roles: [npm]
            vars: { npm_name: {{ create_package }} }
