- import_playbook: packages/ansible-lint/main.yaml
- import_playbook: packages/autopep8/main.yaml
- import_playbook: packages/black/main.yaml
- import_playbook: packages/embedme/main.yaml
- import_playbook: packages/fava/main.yaml
- import_playbook: packages/flake8/main.yaml
- import_playbook: packages/hovercraft/main.yaml
- import_playbook: packages/isort/main.yaml
- import_playbook: packages/js-yaml/main.yaml
- import_playbook: packages/jsonlint/main.yaml
- import_playbook: packages/lint-staged/main.yaml
- import_playbook: packages/pip-tools/main.yaml
- import_playbook: packages/prettier/main.yaml
- import_playbook: packages/reuse/main.yaml
- import_playbook: packages/uncommitted/main.yaml
