# © 2019 Keith Maxwell
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain
# one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
# SPDX-Copyright: 2019 Keith Maxwell
#
- name: Install stable Node.js on Alpine Linux
  become: yes
  when: ansible_distribution == 'Alpine'
  apk: { name: [nodejs, nodejs-doc, npm] }
