- name: Install {{ playbook_dir | basename }} application with pip on localhost
  hosts: localhost
  pre_tasks:
    - name: Install git so that --version works
      become: yes
      package: { name: git }
    - name: Install git fast-import
      become: yes
      package: { name: git-fast-import }
      when: ansible_distribution == 'Alpine'
  roles: [pip]
