- name: Install {{ playbook_dir | basename }} application with pip
  hosts: all
  pre_tasks:
    - name: Install git so that --version works
      become: yes
      package: { name: git }
  roles: [pip]
