- name: Install {{ playbook_dir | basename }} application with pip
  hosts: all
  pre_tasks:
    - name: Install dependencies with compiled extensions on Alpine Linux
      apk:
        name:
          - py3-setuptools # unsafe in a requirements file
          - "py3-virtualenv{{ apk_version | default('~20.4.2') }}" # ./requirements.in
        repository:
          - http://dl-cdn.alpinelinux.org/alpine/edge/main
      when: ansible_distribution == 'Alpine'
  roles: [pip]
