- name: Install {{ playbook_dir | basename }} application with npm on localhost
  hosts: localhost
  vars: { npm_versions: [] }
  roles: [npm]
  tasks:
    - name: Check that jsonlint runs OK, jsonlint --version return code is 1
      command: jsonlint --version
      changed_when: no
      register: npm_version_check
      failed_when: npm_version_check.rc != 1
    - name: View version number
      debug: { msg: "{{ { 'jsonlint --version': npm_version_check.stdout } }}" }
