# © 2019 Keith Maxwell
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain
# one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
# SPDX-Copyright: 2019 Keith Maxwell
#
- name: Create a directory
  become: yes
  file:
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    path: /opt/{{ pip_name }}
- name: Copy in requirements.txt
  become: no
  copy:
    src: requirements.txt
    dest: /opt/{{ pip_name }}/requirements.txt
  notify: New requirements file
  when: "('./packages/'~pip_name~'/requirements.txt') is file"
- meta: flush_handlers
- name: Run the installed binaries
  command: "{{ item }} --version"
  changed_when: no
  loop: "{{ pip_versions|default(pip_binaries|default([pip_name])) }}"
  register: pip_version_check
- name: Show the installed version
  debug:
    msg: |
      {% set output = {} %}
      {% for i in pip_version_check.results %}
      {%   set _ignore = output.update({i.cmd | join(' '): i.stdout}) %}
      {% endfor %}
      {{ output }}
  when: not pip_version_check is skipped
