- name: Apply pip role on localhost
  hosts: localhost
  pre_tasks:
    - name:
        On Alpine Linux, install beancount from the testing repository because
        it includes a parser written in C, on other distributions a wheel is
        available
      apk:
        name: beancount
        repository:
          - http://dl-cdn.alpinelinux.org/alpine/edge/main
          - http://dl-cdn.alpinelinux.org/alpine/edge/community
          - http://dl-cdn.alpinelinux.org/alpine/edge/testing
      when: ansible_distribution == 'Alpine'
  roles: [pip]
