- name: git-revise
  hosts: all
  pre_tasks:
    - name: Install dependencies that don't belong in requirements.txt
      apk:
        name:
          - py3-setuptools
        repository:
          - http://dl-cdn.alpinelinux.org/alpine/edge/main
  roles: [pip]
