- name: Install {{ playbook_dir | basename }} application with pip
  hosts: all
  roles: [pip]
  pre_tasks:
    - name: Install dependencies that don't belong in requirements.txt
      apk:
        name:
          - py3-setuptools
        repository:
          - http://dl-cdn.alpinelinux.org/alpine/edge/main
