# © 2019 Keith Maxwell
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain
# one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
# SPDX-Copyright: 2019 Keith Maxwell
#
- name: Install exact version with npm ci
  become: no
  npm:
    ci: true
    path: /opt/{{ npm_name }}
  listen: New lock file
- name: Install links to binaries
  become: yes
  file:
    state: link
    src: /opt/{{ npm_name }}/node_modules/.bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
  loop: "{{ npm_binaries }}"
  listen: New lock file
