- name: Install {{ playbook_dir | basename }} application with pip on localhost
  hosts: localhost
  vars: { pip_versions: [] }
  roles: [pip]
  tasks:
    - name: Check that uncommitted runs OK, it doesn't support --version
      command: uncommitted --help
      changed_when: no
