- name: Install {{ playbook_dir | basename }} application with pip
  hosts: all
  pre_tasks:
    - name: Install dependencies with compiled extensions on Alpine Linux
      apk:
        name:
          - py3-setuptools
          - "py3-typed-ast{{ apk_version | default('~1.4.2') }}" # ./requirements.in
          - "py3-regex{{ apk_version | default('~2020.11.13') }}" # "
        repository:
          - http://dl-cdn.alpinelinux.org/alpine/edge/main
          - http://dl-cdn.alpinelinux.org/alpine/edge/community
      when: ansible_distribution == 'Alpine'
  roles: [pip]
